# Logo
logo_image_source: http://ww1.sinaimg.cn/large/006eegdsgy1ggvfmjwlhvj302s02s0ik.jpg

# Index Page
index_banner_text: Welcome to my Website
index_banner_text_secondary: Have fun!
index_font_awesome_icon_css: fa fa-magic

# Header
menu:
  主页: /
  所有文章: /archives
  抽号器: /Rank-Int-Machine.html
#  Tags: /tags
#  Categories: /categories
  关于: /about.html
  联系我: /contact.html

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: http://ww1.sinaimg.cn/large/006eegdsgy1ggvfu9dxd9j30u00u0tnb.jpg
about_widget_text: "Hi这里是Dian_Jiao（电教），这里是我的网站<br>我是一个来自偏远小渔村的学生<br> 希望你能在我的网站玩的开心ヾ(≧▽≦*)o"


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
#  - url: https://twitter.com/?lang=en
#    fa_icon: fa-twitter
#  - url: https://www.facebook.com/
#    fa_icon: fa-facebook
#  - url: https://dribbble.com/
#    fa_icon: fa-dribbble 
  - url: https://github.com/Dian-Jiao
    fa_icon: fa-github
#  - url: https://plus.google.com/
#    fa_icon: fa-google-plus
#  - url: https://www.behance.net/
#    fa_icon: fa-behance
#  - url: https://500px.com/
#    fa_icon: fa-500px
#  - url: mailto:test@example.com
#    fa_icon: fa-envelope
#  - url: /#
#    fa_icon: fa-rss

# Footer about
footer_about: "Copyright Dian_Jiao. All right reserved."
